- src/components/common/Button.js
두가지 유형의 Button Component 제작
- Contained Button
- Outlined Button
**필요한 props**
- to : button에 link 이동 기능이 필요하면 to props 전달
- outlined (필수): true (outlined) or false (contained)
- basicColor (필수): contained button이라면 배경색, outlined button이라면 폰트색과 border색
- hover: contained button일 경우 마우스를 올릴 때 나타나는 배경색
참고
- outlined button에 마우스를 올리면 contained button으로 변함.
- styled override 가능
- Button Component UI는 얼마든지 수정 가능
> Button Component

- package-lock.json
- package.json
- src/App.js
@emotion/react와 @emotion/styled 라이브러리 추가 설치
-> m-ui icon 임포트해도 에러 발생 안함.
**develop 브랜치로 fetch해서 동기화한 다음 `npm ci` 명령어 다시 실행하기!!**
> Material UI 관련 버그 수정

- src/components/common/DropBox.js
- src/index.scss
DropBox Component
- color는 임의로 설정
- 얼마든지 style override 가능
- dropbox 펼치고 접는 애니메이션 효과 추가
- option이 많은 경우 scroll해서 볼 수 있음
> DropBox Component

- src/components/common/Header/Logo.js
- src/components/common/Header/NavBar.js
- src/components/common/Header/NavBtn.js
- src/components/common/Header/NavLinks.js
- src/components/common/Header/UserLinks.js
- src/components/common/Header/index.js
- src/constants/index.js
- src/constants/nav.js
- src/index.scss
responsive하게 만듦.
디자인은 얼마든지 변경 가능 (색깔 등등)
> Header Component

- src/components/common/ComboBox.js
파일명과 component이름 수정
(DropBox -> ComboBox)
> DropBox를 ComboBox로 수정

- src/components/common/ComboBox.js
ComboBox Component 컴포넌트 코드 수정
: issue에 올린 그림과 비슷하게 디자인 수정
> ComboBox Component

- src/components/common/Loading.js
> Loading Component

- src/components/common/DropMenu.js
> DropMenu Component

- src/App.js
- src/components/common/ComboBox.js
- src/components/common/DropMenu.js
- src/components/common/Header/index.js
- src/components/common/Loading.js
- src/hooks/index.js
- src/hooks/useToggle.js
**Header Component**
로그인 안했을 시
버튼 클릭 시 메뉴가 펼쳐지고 접히는 애니메이션 보여짐
로그인 했을 시
회원가입 -> 마이페이지
로그인 -> 로그아웃
<br/>
**Button Component**
색깔 얼마든지 변경 가능 (props로 전달)
Contained Button에 마우스 올릴 때 색깔 짙어짐 (짙은 색깔도 props로 전달해야 함)
Oulined Button에 마우스 올릴 때 contained button으로 변함
<br/>
**ComboBox Component**
'증권회사 선택' 문구는 얼마든지 변경 가능 (props로 전달)
버튼 클릭시 option들 볼 수 있음 (이때 펼쳐지고 접히는 애니메이션 적용)
combo box 활성화될 때 변하는 색깔도 변경 가능 (props로 전달)
선택 가능한 option들은 props로 전달 (필수!!)
<br/>
**DropBox Component**
버튼 클릭시 메뉴 볼 수 있음 (이때 펼쳐지고 접히는 애니메이션 적용)
메뉴 리스트 props로 전달 필수!
<br/>
**Loading Component**
> Common Components 수정

- src/containers/LoginFormContainer.js
- src/modules/login.js
로그인 페이지 나갈 시 Login Error 초기화 기능 추가
> Login 로직 수정 with Redux

- src/components/common/Modal.js
> Modal Component

- src/components/Login/LoginFind.js
- src/pages/Login.js
> 비밀번호 찾기 UI

- src/pages/ResetPwd.js
> 비밀번호 재설정 페이지 UI

- src/App.js
- src/components/MyPage/MyCommetItem.js
- src/components/MyPage/MyPostItem.js
- src/components/MyPage/MyPostList.js
- src/components/MyPage/NoList.js
- src/components/MyPage/Notification.js
- src/components/MyPage/NotifyItem.js
- src/components/MyPage/PrivateInfo.js
- src/components/MyPage/SideBar.js
- src/components/MyPage/WithDraw.js
- src/hooks/useToggle.js
- src/pages/MyPage.js
- src/pages/MySubPage.js
디자이너분이 새로 오셔서 UI는 얼마든지 바뀔 수 있음
> 마이페이지 UI 구현

- src/components/Login/LoginFind.js
- src/components/Login/LoginForm.js
- src/components/MyPage/WithDraw.js
- src/components/common/FormInput.js
- src/pages/ResetPwd.js
FormInput Component 구현하여 필요한 곳에 import해서 적용함.
총 9개의 props를 전달받음.
- label (선택)
- labelIcon (선택)
- type (필수)
- name (필수)
- value (필수)
- placeholder (선택)
- onChange 함수 (필수)
- error (선택)
- errorMessage (error props를 전달했다면 필수)
> FormInput Component

- src/App.js
- src/components/Login/SocialLogin.js
- src/pages/Home.js
- src/pages/Login.js
> Login Page 수정

- src/pages/MoneyBook.js
> 가계부 페이지 전체 UI 구현

- src/components/MyPage/PersonalInfoChangeForm.js
은비님, 제가 커밋 취소 누르다가 마지막에 은비님이 피드백 주셔서 반영한 부분까지 취소가 되었어요..
그래서 다시 풀 리퀘스트 날릴게요ㅠㅠ
가계부 설정 UI는 다른 브랜치 파서 작업할게요!
> 개인정보 UI 구현(누락된 커밋 추가)

- src/components/Community/CommentItem.js
- src/components/Community/CommentList.js
- src/components/common/Modal.js
- src/components/common/NotLogin.js
- src/hooks/useNotLogin.js
- src/pages/CommunityPage/CommunityListPage.js
로그인 하지 않았을 경우 
- 글 작성 불가
- 댓글 및 대댓글 달기 불가
- 좋아요 및 스크랩 불가
> 커뮤니티 페이지에 login 권한 로직 추가

- src/components/Community/CommentForm.js
- src/components/common/TextArea.js
- 여러 줄로 작성할 수 있도록 text에서 textarea로 변경
> 댓글 input textarea로 변경

- src/components/Community/ImagePreview.js
- src/components/common/Editor.js
- src/index.scss
- src/pages/CommunityPage/CommunitySubPage.js
> 게시글 작성 UI 수정

- src/pages/CommunityPage/CommunityWritePage.js
> 이미지 업로드 기능 추가

- src/components/Community/BoardDetail.js
- src/components/Community/CommentItem.js
- src/constants/nav.js
- src/pages/CommunityPage/index.js
- src/pages/MoneyBook.js
- src/pages/MyPage/index.js
- mypage menu
- community page menu
- moneybook page menu
- community detail page의 drop menu
> menu 상수들을 constants/nav.js로 옮김

- src/components/MyPage/PersonalInfoChangeForm.js
> 마이페이지 UI 중 개인정보 UI 페이지 변경

- src/components/Login/OauthRedirect.js
- src/components/common/Header/UserLinks.js
- src/lib/api/auth.js
- `Authorization`에 token `set`
- 만료시간 확인하여 만료시간이 지나면 `reissue api` 호출하여 새로운 `access token` 받는 로직도 추가
> header에 token 넣는 로직 추가

- src/App.js
`localStorage`에 `token`이 있는지 확인하고 있다면 `store`에 있는 `auth` 상태값 업데이트하여 로그인 유지
> 새로고침해도 로그인 유지되는 로직 추가

- src/containers/EditorContainer.js
- src/lib/api/post.js
- src/modules/post.js
- src/pages/CommunityPage/CommunityWritePage.js
> 게시물 작성 페이지에 api 적용

- src/components/Community/CommentForm.js
- src/components/Community/CommentItem.js
- src/components/Community/CommentList.js
- src/components/Community/PostDetail.js
- src/components/Community/PostDropMenu.js
- src/containers/CommentFormContainer.js
- src/containers/PostDetailContainer.js
- src/lib/api/comment.js
- src/modules/comment.js
- src/pages/CommunityPage/CommunityDetailPage.js
- src/pages/CommunityPage/CommunitySubPage.js
- 게시물 단건 조회 `GET` api 적용
- 좋아요 api 적용
- 댓글 `POST` `PATCH` `DELETE` api 적용
> 게시물 상세 페이지 api 적용

- src/components/Community/PostItem.js
> 게시글 목록 아이템 디자인 수정

- src/components/MyPage/MyCommetItem.js
- src/components/MyPage/MyPostItem.js
- src/components/MyPage/MyPostList.js
- src/lib/api/user.js
- 내가 쓴 글 및 댓글  `DELETE` api 적용
- 스크랩 취소 api 적용
> 마이페이지에 api 적용 완료

- src/components/Community/ImageList.js
- src/components/common/Editor.js
- src/components/common/ImagePreview.js
- src/containers/EditorContainer.js
- src/lib/api/post.js
- src/modules/post.js
- src/pages/CommunityPage/CommunityWritePage.js
- `useMutation` 이용
- `saveImageUrl`과 `imageFiles` 상태값 구분
> 게시물 수정 api 적용

- src/components/FinancialLedger/SetExpenseRatio.js
가계부 설정 UI에서 지출 비율을 설정할 때, 값이 화면에 표시되지 않는 에러를 수정했습니다.
> 가계부 설정 UI에서 지출 비율 설정 수정

- src/pages/FinancialLedgerPage/FinancialLedgerSubPage.js
- src/pages/FinancialLedgerPage/Setting.js
FinancialLedgerSubpage에 SettingPage를 추가하였습니다.
> FinancialLedgerSubpage에 SettingPage를 추가

- src/components/Community/PostItem.js
> 커뮤니티 auth 로직 수정

- src/lib/api/post.js
- 게시물 단건 조회 api 요청 전 헤더에 token 설정
> 커뮤니티 api 요청 수정

- src/components/FinancialLedger/HistoryMain.js
- src/components/FinancialLedger/HistoryMainItem.js
- src/lib/api/history.js
- `useQuery` 이용하여 GET api 적용
- `error` 발생하면 설정 페이지로 `redirect`
> 수익지출관리 GET api 적용

- src/pages/FinancialLedgerPage/index.js
- 로그인 하지 않은 상태에서는 가계부 기능 사용 불가
> 가계부 auth 로직 수정

- src/components/FinancialLedger/CategoryItem.js
- src/components/FinancialLedger/CategoryList.js
- src/components/FinancialLedger/InsertCategory.js
- src/components/FinancialLedger/SetCategory.js
- src/components/FinancialLedger/StyledComponentInSetting.js
- src/pages/FinancialLedgerPage/SettingPage.js
가운데 정렬 지정했으나 제대로 반영되지 않아 다시 수정했습니다..
> 가계부 UI를 가운데 정렬

- src/components/FinancialLedger/SetCategory.js
- src/components/FinancialLedger/SetExpenseRatio.js
- src/components/FinancialLedger/SetMonthlyBudget.js
- src/containers/BudgetContainer.js
- src/containers/CategoryContainer.js
- src/containers/ExpenseContainer.js
- src/modules/budget.js
- src/modules/category.js
- src/modules/expense.js
- src/modules/index.js
- src/pages/FinancialLedgerPage/SettingPage.js
> 가계부 설정 페이지에 Redux 적용

- src/components/FinancialLedger/CategoryItem.js
- src/components/FinancialLedger/CategoryList.js
- src/components/FinancialLedger/InsertCategory.js
- src/components/FinancialLedger/SetCategory.js
- src/components/FinancialLedger/SetExpenseRatio.js
- src/components/FinancialLedger/SetMonthlyBudget.js
- src/constants/category.js
- src/containers/BudgetContainer.js
- src/containers/CategoryContainer.js
- src/containers/ExpenseContainer.js
- src/modules/budget.js
- src/modules/category.js
- src/modules/expense.js
- src/pages/FinancialLedgerPage/SettingPage.js
- src/pages/FinancialLedgerPage/index.js
> 가계부 설정 페이지 redux 적용 및 api 적용

- src/components/FinancialLedger/StyledComponentInSetting.js
설정 페이지의 `styled component` 코드 조금 수정했습니다.
> 가계부 설정 페이지 UI 수정

- src/components/FinancialLedger/SetExpenseRatio.js
- src/containers/BudgetContainer.js
- src/containers/ExpenseContainer.js
- src/modules/expense.js
- src/pages/FinancialLedgerPage/index.js
- 예산 `GET` api와 지출비율 `GET` api가 없어서 `localStorage`에 저장하는 로직 추가
> 가계부 예산/지출비율 설정 로직 수정

- src/components/FinancialLedger/HistoryForm.js
- src/components/FinancialLedger/HistoryMain.js
- src/components/FinancialLedger/HistoryMainItem.js
- src/components/FinancialLedger/HistoryMainList.js
- src/components/common/ComboBox.js
- src/containers/HistoryFormContainer.js
- src/containers/HistoryMainContainer.js
- src/lib/api/history.js
- src/modules/history.js
- `GET`
- `POST`
- `PATCH`
- `DELETE`
> 수익 지출 관리 페이지 api 적용

- src/components/FinancialLedger/SetMonthlyBudget.js
- src/containers/HistoryMainContainer.js
- src/pages/FinancialLedgerPage/SettingPage.js
- 예산 설정이 안되어 있으면 수익 지출 `GET` api에서 오류가 발생하는데 이에 대한 처리 로직 수정
> 수익 지출 관리 페이지 GET api 오류 로직 수정

- src/components/FinancialLedger/HistoryMain.js
- 수익 지출 내역이 없는 경우 수익지출 내역이 없다는 문구 보여줌
> 가계부 수익 지출 관리 페이지 UI 수정

- package-lock.json
- package.json
- src/index.js
- src/modules/index.js
- 에디터 관련 패키지 삭제
- `redux-thunk` 삭제
- `redux-saga` 삭제
- `json-server` 삭제
> 불필요한 패키지 삭제 및 관련 코드 수정

- src/components/FinancialLedger/CategoryItem.js
- src/components/FinancialLedger/SetCategory.js
- src/components/FinancialLedger/SetMonthlyBudget.js
- src/components/FinancialLedger/StyledComponentInSetting.js
- src/components/common/Modal.js
- font size 조금 크게 변경
- `category list`에서 border color `lightgray`로 변경
- `Modal` 컴포넌트 스크롤 가능하게 변경
> 설정 페이지 UI 수정

- src/components/Community/PostDetail.js
- src/components/FinancialLedger/MoneyLog.js
- src/components/FinancialLedger/MoneyLogAssetGoal.js
- src/components/FinancialLedger/MoneyLogForm.js
- src/components/FinancialLedger/MoneyLogGuide.js
- src/components/common/Editor.js
- src/components/common/ImageList.js
- src/containers/MoneyLogContainer.js
- src/lib/api/moneylog.js
- src/lib/api/setting.js
> 머니로그 페이지 api 적용 및 그에 따른 UI 변경

- src/modules/post.js
- src/pages/CommunityPage/CommunityWritePage.js
- 머니로그 이미지 `url`를 `file object`로 변환하는 작업 필요
> 머니로그 커뮤니티 공유 기능 수정

- src/containers/HistoryMainContainer.js
> 수익지출 관리 페이지 UI 수정

- src/components/FinancialLedger/MoneyLog.js
- src/components/FinancialLedger/MoneyLogAssetGoal.js
- src/components/common/Editor.js
- src/components/common/ImageList.js
- src/components/common/ImagePreview.js
- src/containers/MoneyLogContainer.js
- src/lib/api/post.js
- src/modules/post.js
- src/pages/CommunityPage/CommunityWritePage.js
- 머니로그에 등록된 이미지 `url`이 게시물에도 등록될 수 있도록 코드 수정
-  커뮤니티 `api` 적용 코드
- `redux` 상태값 수정
> 머니로그 공유하기 기능 수정 및 UI 수정

- src/components/FinancialLedger/MoneyLog.js
- src/components/FinancialLedger/MoneyLogGuide.js
- src/pages/FinancialLedgerPage/MoneyLogPage.js
- `overflow`, `scroll` 관련 디자인 수정
> 머니로그 페이지 UI 수정

- src/components/FinancialLedger/HistoryForm.js
- src/components/FinancialLedger/HistoryMainItem.js
- src/components/FinancialLedger/HistoryMainList.js
- src/containers/HistoryFormContainer.js
> 수익지출 관리 페이지 UI 수정 및 그에 따른 api 적용 코드 수정

- src/containers/HistoryMainContainer.js
- src/containers/MoneyLogContainer.js
> useQuery retry 옵션 false에서 1로 수정

- src/components/FinancialLedger/MoneyLogGuide.js
- `toLocaleString()` 이용하여 천원 단위마다 `,` 추가
> 머니로그 페이지 수익지출 목록 UI 수정

- src/components/Community/PostDetail.js
- src/components/FinancialLedger/MoneyLog.js
- src/lib/index.js
- `api` 요청해서 받은 데이터는 일반 문자열이라서 link도 문자열로 처리됨
- 정규식 이용하여 자동으로 link 처리되도록 코드 수정
> 커뮤니티 및 머니로그 글에서 link부분 자동으로 하이퍼링크로 처리

- src/App.js
- src/components/MyPage/PersonalInfoChangeForm.js
> 마이페이지 중 개인정보 변경 UI 변경

- src/components/Community/PostItem.js
- src/components/FinancialLedger/HistoryForm.js
- src/components/FinancialLedger/HistoryMain.js
- src/components/FinancialLedger/HistoryMainItem.js
- src/components/FinancialLedger/MoneyLog.js
- src/components/FinancialLedger/MoneyLogGuide.js
- src/components/FinancialLedger/StyledComponentInSetting.js
- src/components/common/Calender.js
- src/components/common/Header/UserLinks.js
- src/components/common/ImageList.js
- src/components/common/SideBar.js
- src/containers/HistoryFormContainer.js
- src/containers/HistoryMainContainer.js
- src/lib/api/statistic.js
- src/pages/CommunityPage/index.js
- src/pages/FinancialLedgerPage/FinancialLedgerSubPage.js
- src/pages/FinancialLedgerPage/HistoryPage.js
- src/pages/FinancialLedgerPage/MoneyLogPage.js
- src/pages/FinancialLedgerPage/SettingPage.js
- src/pages/FinancialLedgerPage/index.js
- 태블릿 및 데스크탑 디바이스 크기에 맞춰 반응형 웹 디자인 적용
> 반응형 웹 디자인 적용

- src/components/FinancialLedger/ComparisonModal.js
- src/components/FinancialLedger/MonthStatistic.js
- src/components/FinancialLedger/StatisticStyled.js
- src/components/FinancialLedger/WeekStatistic.js
- src/components/FinancialLedger/YearStatistic.js
- src/components/common/BarGraph.js
- src/components/common/ImageList.js
- src/constants/index.js
- src/containers/StatisticContainer.js
- src/lib/utils.js
- src/modules/post.js
- src/pages/FinancialLedgerPage/StatisticPage.js
> 통계 공유하기 기능 추가

- src/components/FinancialLedger/HistoryForm.js
- src/components/FinancialLedger/HistoryMainItem.js
- src/containers/HistoryFormContainer.js
- src/lib/api/history.js
- src/modules/history.js
> 가계부 수익지출 내역 추가 및 수정 로직 수정

- src/components/FinancialLedger/WeekStatistic.js
- 일주일 통계 api 요청 시 넣는 쿼리 스트링 값 에러 수정
> Fix: 일주일 통계 api 요청 코드 수정
